/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectalpha;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import javax.swing.JOptionPane;
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.usermodel.CharacterRun;
import org.apache.poi.hwpf.usermodel.Paragraph;
import org.apache.poi.hwpf.usermodel.Range;
import org.apache.poi.hwpf.usermodel.Section;

/**
 *
 * @author kartikya
 */
public class form6upi extends javax.swing.JFrame {

    /**
     * Creates new form form6upi
     */
    public form6upi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GPAY = new javax.swing.JRadioButton();
        PHONEPE = new javax.swing.JRadioButton();
        PAYTM = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtupi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setText("BHIM-UPI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 31, 437, 31));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setText("CHOOSE UPI APP :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 98, -1, -1));

        GPAY.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        GPAY.setText("GOOGLE PAY");
        GPAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPAYActionPerformed(evt);
            }
        });
        getContentPane().add(GPAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 129, 150, -1));

        PHONEPE.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        PHONEPE.setText("PHONEPE");
        PHONEPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHONEPEActionPerformed(evt);
            }
        });
        getContentPane().add(PHONEPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 177, 139, -1));

        PAYTM.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        PAYTM.setText("PAYTM");
        PAYTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAYTMActionPerformed(evt);
            }
        });
        getContentPane().add(PAYTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 225, 98, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setText("ENTER UPI ID : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        getContentPane().add(txtupi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 262, 30));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setText("AMOUNT TO BE PAID : RS.300/- (incl GST)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 24));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButton1.setText("PAY & GENERATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectalpha/Screenshot 2023-10-27 193303.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GPAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPAYActionPerformed
        // TODO add your handling code here:
        
        if(GPAY.isSelected())
        {
            PHONEPE.setSelected(false);
            PAYTM.setSelected(false);
        }
    }//GEN-LAST:event_GPAYActionPerformed

    private void PHONEPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHONEPEActionPerformed
        // TODO add your handling code here:
        if(PHONEPE.isSelected())
        {
            GPAY.setSelected(false);
            PAYTM.setSelected(false);
        }
    }//GEN-LAST:event_PHONEPEActionPerformed

    private void PAYTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAYTMActionPerformed
        // TODO add your handling code here:
        if(PAYTM.isSelected())
        {
            PHONEPE.setSelected(false);
            GPAY.setSelected(false);
        }
    }//GEN-LAST:event_PAYTMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        form f=new form();
        form2 f2=new form2();
        form3 f3=new form3();
String name=f.txtname.getText();
String email=f.txtemail.getText();
String phn=f.txtph.getText();
String add=f.txtloc.getText();
//Education
String edu=f2.txtedu.getText();
//Work Experience
String we=f2.txtwe.getText();
//SKILLS
String skl=f3.txtskl.getText();
//Achievements
String ach=f3.txtach.getText();
//Certifications
String cft=f3.txtcft.getText();

try{
     form3 instance = new form3();
        HWPFDocument doc = instance.openDocument(location);
        if (doc != null) {            
            //General
            doc = instance.replaceText(doc, "<NAME>",name);
            doc = instance.replaceText(doc, "<EMAIL>",email);           
            doc = instance.replaceText(doc, "<PHONE>",phn);
            doc = instance.replaceText(doc, "<ADDRESS>",add);
            //Education
            doc = instance.replaceText(doc, "<EDUCATION>",edu);
            //WORK EXPERIENCE
            doc = instance.replaceText(doc, "<WORK EXPERIENCE>",we);
            //SKILLS
            doc = instance.replaceText(doc, "<SKILLS>",skl);
            //CERTIFICATIONS
            doc = instance.replaceText(doc, "<CERTIFICATIONS>",cft);
            //ACHIEVEMENTS
            doc = instance.replaceText(doc, "<ACHIEVEMENTS>",ach);
            
            instance.saveDocument(doc, "C:\\Users\\kartikya\\Desktop\\template"+name+"_cv.doc");//location whee you want to save the file
            JOptionPane.showMessageDialog(this, "cv generated!!! check desktop");
        }
          
            }
catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        form4 f= new form4();
        f.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form6upi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form6upi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form6upi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form6upi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form6upi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GPAY;
    private javax.swing.JRadioButton PAYTM;
    private javax.swing.JRadioButton PHONEPE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtupi;
    // End of variables declaration//GEN-END:variables

private HWPFDocument replaceText(HWPFDocument doc, String findText, String replaceText) {
        Range r = doc.getRange();
        for (int i = 0; i < r.numSections(); ++i) {
            Section s = r.getSection(i);
            for (int j = 0; j < s.numParagraphs(); j++) {
                Paragraph p = s.getParagraph(j);
                for (int k = 0; k < p.numCharacterRuns(); k++) {
                    CharacterRun run = p.getCharacterRun(k);
                    String text = run.text();
                    if (text.contains(findText)) {
                        run.replaceText(findText, replaceText);
                    }
                }
            }
        }
        return doc;
    }

    private HWPFDocument openDocument(String file) throws Exception {
        URL res = getClass().getClassLoader().getResource(file);
        HWPFDocument document =  new HWPFDocument(new FileInputStream(location));                             
        return document;
    }

    private void saveDocument(HWPFDocument doc, String file) {
        try (
                FileOutputStream out = new FileOutputStream(file)) {
            doc.write(out);          
        } catch (IOException e) {
        }
    }
    public static String location;    
    static String file_loc1 ="./src/projectalpha/TEMPLATE1.doc" ;
    static String file_loc2 = "./src/projectalpha/TEMPLATE 2.doc";
    static String file_loc3 = "./src/projectalpha/RES_TEMPLATE1.doc";
}
