/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectalpha;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.usermodel.CharacterRun;
import org.apache.poi.hwpf.usermodel.Paragraph;
import org.apache.poi.hwpf.usermodel.Range;
import org.apache.poi.hwpf.usermodel.Section;




/**
 *
 * @author kartikya
 */
public class form3 extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement ps;
    String query; 

    /**
     * Creates new form form3
     */
    public form3() {
        try {
           
            initComponents();
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","0Ne_pUNCH");
            } catch (SQLException ex) {
                Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
            }
            query="delete from res3";
            try {
                ps=con.prepareStatement(query);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        save = new javax.swing.JButton();
        generate_resume = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtskl = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtach = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcft = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setText("SKILLS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 37, -1, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel2.setText("ACHIEVEMENTS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 211, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel3.setText("CERTIFICATIONS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 370, -1, -1));

        back.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 549, -1, -1));

        save.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 549, -1, -1));

        generate_resume.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        generate_resume.setText("GO TO PAYMENTS");
        generate_resume.setActionCommand("");
        generate_resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_resumeActionPerformed(evt);
            }
        });
        getContentPane().add(generate_resume, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 549, -1, -1));

        txtskl.setColumns(20);
        txtskl.setRows(5);
        jScrollPane1.setViewportView(txtskl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 80, 769, -1));

        txtach.setColumns(20);
        txtach.setRows(5);
        jScrollPane2.setViewportView(txtach);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 254, 769, -1));

        txtcft.setColumns(20);
        txtcft.setRows(5);
        jScrollPane3.setViewportView(txtcft);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 413, 769, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectalpha/Screenshot 2023-10-27 193303.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int yes=JOptionPane.showConfirmDialog(this,"You will go back and all data entered will be lost","confirm!!!",JOptionPane.YES_NO_OPTION);
       if(JOptionPane.YES_OPTION==yes)
       {  
        form2 f=new form2();
        f.show();
        
        dispose();
       }
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            // TODO add your handling code here:
            query="insert into res3 values (?,?,?)";
            ps=con.prepareStatement(query);
            ps.setString(1,txtskl.getText());
            ps.setString(2,txtach.getText());
            ps.setString(3,txtcft.getText());
            
            int res=ps.executeUpdate();
            
            if(res==1)
            {
                JOptionPane.showMessageDialog(this,"All attributes ready , proceed to choose tempelate and generate a pdf!!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void generate_resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_resumeActionPerformed
        //General Details
    
form4 f=new form4();
f.show();
dispose();
        

    }//GEN-LAST:event_generate_resumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(() -> {
            new form3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton generate_resume;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton save;
    public javax.swing.JTextArea txtach;
    public javax.swing.JTextArea txtcft;
    public javax.swing.JTextArea txtskl;
    // End of variables declaration//GEN-END:variables
 HWPFDocument replaceText(HWPFDocument doc, String findText, String replaceText) {
        Range r = doc.getRange();
        for (int i = 0; i < r.numSections(); ++i) {
            Section s = r.getSection(i);
            for (int j = 0; j < s.numParagraphs(); j++) {
                Paragraph p = s.getParagraph(j);
                for (int k = 0; k < p.numCharacterRuns(); k++) {
                    CharacterRun run = p.getCharacterRun(k);
                    String text = run.text();
                    if (text.contains(findText)) {
                        run.replaceText(findText, replaceText);
                    }
                }
            }
        }
        return doc;
    }

    HWPFDocument openDocument(String file) throws Exception {
        URL res = getClass().getClassLoader().getResource(file);
        HWPFDocument document =  new HWPFDocument(new FileInputStream(location));                             
        return document;
    }

    void saveDocument(HWPFDocument doc, String file) {
        try (
                FileOutputStream out = new FileOutputStream(file)) {
            doc.write(out);          
        } catch (IOException e) {
        }
    }
    public static String location;    
    static String file_loc1 ="./src/projectalpha/TEMPLATE1.doc" ;
    static String file_loc2 = "./src/projectalpha/TEMPLATE 2.doc";
    static String file_loc3 = "./src/projectalpha/RES_TEMPLATE1.doc";
}
