/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectalpha;

import java.sql.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.usermodel.CharacterRun;
import org.apache.poi.hwpf.usermodel.Paragraph;
import org.apache.poi.hwpf.usermodel.Range;
import org.apache.poi.hwpf.usermodel.Section;

/**
 *
 * @author kartikya
 */
public class form7card extends javax.swing.JFrame {

    /**
     * Creates new form form7card
     */
    
    Connection con;
    PreparedStatement ps1,ps2,ps3;
    String query1,query2,query3;
    ResultSet rs1,rs2,rs3;
    public form7card() {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/host","root","0Ne_pUNCH");
                 query1="Select * from res";
                query2="Select * from res1";
                query3="Select * from res3";
                
                ps1=con.prepareStatement(query1);
                  ps2=con.prepareStatement(query2);
                    ps3=con.prepareStatement(query3);
                
                rs1=ps1.executeQuery();
                rs2=ps2.executeQuery();
                rs3=ps3.executeQuery();
            } catch (SQLException ex) {
                Logger.getLogger(form7card.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            initComponents();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(form7card.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ctxt = new javax.swing.JTextField();
        mtxt = new javax.swing.JTextField();
        cvv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel1.setText("CARD PAYMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        jLabel2.setText("ENTER CARD NUMBER ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 148, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        jLabel3.setText("ENTER MOBILE NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 191, -1, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        jLabel4.setText("CVV");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 234, 37, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel5.setText("THE AMOUNT TO PAID IS :- RS.300\\-(incl GST)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 307, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton1.setText("PAY & GENERATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 345, 224, -1));

        jButton2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 345, -1, -1));
        getContentPane().add(ctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 151, 207, -1));

        mtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtxtActionPerformed(evt);
            }
        });
        getContentPane().add(mtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 191, 207, -1));
        getContentPane().add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 234, 71, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectalpha/Screenshot 2023-10-27 193303.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String m=mtxt.getText();
        String cv=cvv.getText();
        String c=ctxt.getText();
        
        if(m.length()==10)
        {
            if(c.length()==16)
            {
                if(cv.length()==3)
                {
                       
       
        String name;
        String email;
        String phn;
        String add;
        //Education
        String edu;
        //Work Experience
        String we;
        //SKILLS
        String skl;
        //Achievements
        String ach;
        //Certifications
        String cft;

        
  /*
try{
     form3 instance = new form3();
        HWPFDocument doc = instance.openDocument(location);
        if (doc != null) {            
            //General
            doc = instance.replaceText(doc, "<NAME>",name);
            doc = instance.replaceText(doc, "<EMAIL>",email);           
            doc = instance.replaceText(doc, "<PHONE>",phn);
            doc = instance.replaceText(doc, "<ADDRESS>",add);
            //Education
            doc = instance.replaceText(doc, "<EDUCATION>",edu);
            //WORK EXPERIENCE
            doc = instance.replaceText(doc, "<WORK EXPERIENCE>",we);
            //SKILLS
            doc = instance.replaceText(doc, "<SKILLS>",skl);
            //CERTIFICATIONS
            doc = instance.replaceText(doc, "<CERTIFICATIONS>",cft);
            //ACHIEVEMENTS
            doc = instance.replaceText(doc, "<ACHIEVEMENTS>",ach);
            
            instance.saveDocument(doc, "C:\\Users\\kartikya\\Desktop\\template"+name+"_cv.doc");//location whee you want to save the file
            JOptionPane.showMessageDialog(this, "cv generated!!! check desktop");
        }
          
            }
catch (Exception e){
    JOptionPane.showMessageDialog(null, e);
}*/



                }
                
//                else
//                {
//                    JOptionPane.showMessageDialog(this,"INCORRECT INFO!! ");
//                    cvv.setText(" ");
//                    ctxt.setText(" ");
//                    mtxt.setText(" ");
//                }
            }
            else
                {
                    JOptionPane.showMessageDialog(this,"INCORRECT INFO!! ");
                    cvv.setText(" ");
                    ctxt.setText(" ");
                    mtxt.setText(" ");
                }
        }
        else
                {
                    JOptionPane.showMessageDialog(this,"INCORRECT INFO!! ");
                    cvv.setText(" ");
                    ctxt.setText(" ");
                    mtxt.setText(" ");
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        form4 f= new form4();
        f.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form7card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form7card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form7card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form7card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new form7card().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ctxt;
    private javax.swing.JTextField cvv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField mtxt;
    // End of variables declaration//GEN-END:variables

HWPFDocument replaceText(HWPFDocument doc, String findText, String replaceText) {
        Range r = doc.getRange();
        for (int i = 0; i < r.numSections(); ++i) {
            Section s = r.getSection(i);
            for (int j = 0; j < s.numParagraphs(); j++) {
                Paragraph p = s.getParagraph(j);
                for (int k = 0; k < p.numCharacterRuns(); k++) {
                    CharacterRun run = p.getCharacterRun(k);
                    String text = run.text();
                    if (text.contains(findText)) {
                        run.replaceText(findText, replaceText);
                    }
                }
            }
        }
        return doc;
    }

    HWPFDocument openDocument(String file) throws Exception {
        URL res = getClass().getClassLoader().getResource(file);
        HWPFDocument document =  new HWPFDocument(new FileInputStream(location));                             
        return document;
    }

    void saveDocument(HWPFDocument doc, String file) {
        try (
                FileOutputStream out = new FileOutputStream(file)) {
            doc.write(out);          
        } catch (IOException e) {
        }
    }
    public static String location;    
    static String file_loc1 ="./src/projectalpha/TEMPLATE1.doc" ;
    static String file_loc2 = "./src/projectalpha/TEMPLATE 2.doc";
    static String file_loc3 = "./src/projectalpha/RES_TEMPLATE1.doc";
}
